overworld:
  world-name: 'world'
  allowed-biomes:
    - 'PLAINS'
nether:
  world-name: 'world_nether'
  allowed-biomes:
    - 'NETHER_WASTES'
end-world-name: 'world_the_end'

radius:
  x: 1000
  z: 1000